/**
 * 
 * This is a restful web service used to log hours for non-profits to submit for money grants.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface Organization {
    organizationId: string;
    name: string;
    description: string;
    email: string;
    phoneNumber: string;
    websiteUrl?: string;
    facebookUrl?: string;
    twitterUrl?: string;
    instagramUrl?: string;
}
