/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface Organization {
    address1?: string;
    city?: string;
    description?: string;
    email?: string;
    facebookUrl?: string;
    instagramUrl?: string;
    name?: string;
    orgGuid?: string;
    phoneNumber?: string;
    state?: string;
    twitterUrl?: string;
    websiteUrl?: string;
    zip?: string;
}
